title = "Tokay"
base_url = "/"
compile_sass = true
build_search_index = false
insert_anchor_links = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "kronuz"
extra_syntaxes_and_themes = [
    "syntax"
]

[extra]
logo_path = "tokay-logo.svg"
logo_name = "Tokay Programming Language"

menu = [
    { title = "About", link = "/about"},
    { title = "News", link = "/news"},
    { title = "Getting started", link = "/getting-started"},
    { title = "Documentation", link = "/tokay-docs"},
    { title = "GitHub", link = "https://github.com/tokay-lang/tokay"}
]
